# Generated by Django 3.1.4 on 2021-01-06 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en_us', models.CharField(max_length=100, null=True)),
                ('name_es', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=200)),
                ('desc_en_us', models.CharField(max_length=200, null=True)),
                ('desc_es', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('name_en_us', models.CharField(max_length=25, null=True)),
                ('name_es', models.CharField(max_length=25, null=True)),
                ('desc', models.CharField(max_length=200)),
                ('desc_en_us', models.CharField(max_length=200, null=True)),
                ('desc_es', models.CharField(max_length=200, null=True)),
                ('stock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=11)),
                ('image', models.ImageField(default='default.jpg', upload_to='pics')),
                ('isApproved', models.BooleanField(default=False)),
                ('User_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='UID', to=settings.AUTH_USER_MODEL)),
                ('categories_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.categories')),
            ],
        ),
    ]
