# Generated by Django 3.1.5 on 2021-01-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Sedan'), (2, 'Truck'), (4, 'SUV')])),
            ],
        ),
        migrations.RemoveField(
            model_name='categories',
            name='desc_en_us',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='desc_es',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='name_en_us',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc_en_us',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en_us',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_es',
        ),
    ]
