# Generated by Django 3.1.5 on 2021-01-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210113_1211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
