# Generated by Django 3.1.4 on 2020-12-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201217_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_en_us',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_es',
        ),
    ]
