# Generated by Django 3.1.4 on 2020-12-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='isActive',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
