# Generated by Django 3.1.4 on 2020-12-10 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0003_auto_20201208_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=200)),
                ('city', models.TextField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('Users_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='UserID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
