# Generated by Django 3.1.4 on 2020-12-03 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=200)),
                ('city', models.TextField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('purchases_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_ID', to='purchase.purchases')),
            ],
        ),
    ]
