# Generated by Django 3.1.4 on 2020-12-10 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='purchases_ID',
        ),
        migrations.AddField(
            model_name='shipping',
            name='Users_ID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='UserID', to=settings.AUTH_USER_MODEL),
        ),
    ]
