# Generated by Django 3.1.4 on 2021-01-06 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=200)),
                ('city', models.TextField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('Users_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='UserID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('Users_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Users_ID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPurchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=3)),
                ('price', models.DecimalField(decimal_places=3, max_digits=9)),
                ('product_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_ID', to='store.product')),
                ('purchases_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Purchase_ID', to='purchases.purchases')),
            ],
        ),
    ]
