# Generated by Django 3.1.4 on 2020-12-08 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_quantity'),
        ('purchase', '0002_auto_20201208_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchases',
            name='product_ID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Product_ID', to='store.product'),
        ),
    ]
