# Generated by Django 3.1.4 on 2020-12-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20201208_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
